from pathlib import Path
from html import escape
from city_seo import city_details
root=Path('dist')
index=root/'index.html'
s=index.read_text()
css=s.split('<style>',1)[1].split('</style>',1)[0]
page_form_css="""/* page-form */.subhero.form-hero{padding:32px 0;min-height:0}.subhero.form-hero .wrap{display:grid;grid-template-columns:minmax(0,1fr) minmax(370px,470px);gap:50px;align-items:center}.subhero.form-hero.city-hero{min-height:690px}.page-hero-copy{padding:30px 0}.page-hero-copy h1{font-size:clamp(2.5rem,4vw,4rem);max-width:600px}.page-hero-copy p{max-width:570px}.subhero.form-hero .hero-form{margin:12px 0}.subhero.form-hero .hero-form .card{color:#172638}.subhero.form-hero .hero-form .card p{color:#526276}.subhero.form-hero .hero-form .card .note{color:#637283}@media(max-width:920px){.subhero.form-hero .wrap{grid-template-columns:1fr;gap:0}.page-hero-copy{padding:25px 0 0}.subhero.form-hero .hero-form{max-width:650px;width:100%;margin:12px 0 28px}}@media(max-width:760px){.subhero.form-hero.city-hero{min-height:0}.subhero.form-hero{padding:25px 0}.page-hero-copy h1{font-size:clamp(2.55rem,9vw,3.5rem)}}"""
if '/* page-form */' not in css:
    css += page_form_css
if '/* city-images */' not in css:
    css += "/* city-images */.subhero.form-hero.city-hero{background-image:linear-gradient(90deg,rgba(16,31,48,.96),rgba(16,31,48,.74) 48%,rgba(16,31,48,.35)),var(--hero-image);background-size:cover;background-position:center}.city-breda{--hero-image:url('/hero-breda.webp')}.city-amsterdam{--hero-image:url('/hero-amsterdam.webp')}.city-rotterdam{--hero-image:url('/hero-rotterdam.webp')}.city-utrecht{--hero-image:url('/hero-utrecht.webp')}.city-denhaag{--hero-image:url('/hero-denhaag.webp')}.city-eindhoven{--hero-image:url('/hero-eindhoven.webp')}.city-tilburg{--hero-image:url('/hero-tilburg.webp')}.city-groningen{--hero-image:url('/hero-groningen.webp')}.city-klundert{--hero-image:url('/hero-klundert.webp')}"
if '.city-klundert{' not in css:
    css += ".city-klundert{--hero-image:url('/hero-klundert.webp')}"
nav='''<header class="top"><div class="wrap"><a class="brand" href="/" aria-label="Loodgieter Vakmannen, naar home"><img src="/logo.svg" alt="Loodgieter Vakmannen" width="292" height="48"></a><nav class="nav" aria-label="Hoofdnavigatie"><span class="nav-pages"><a href="/#gemeenten">Gemeenten</a><a href="/over-ons/">Over ons</a><a href="/contact/">Contact</a></span><a class="smallbtn" href="#aanvraag">Doe een aanvraag</a></nav></div></header>'''
footer='''<footer class="foot"><div class="wrap"><div><a class="brand" href="/"><img src="/logo.svg" alt="Loodgieter Vakmannen" width="292" height="48"></a><p>Een initiatief van Star Local. Aanvragen worden via WhatsApp verstuurd.</p><div class="footerlinks"><a href="/loodgieter-breda/">Breda</a><a href="/loodgieter-amsterdam/">Amsterdam</a><a href="/loodgieter-rotterdam/">Rotterdam</a><a href="/loodgieter-utrecht/">Utrecht</a><a href="/loodgieter-denhaag/">Den Haag</a><a href="/loodgieter-eindhoven/">Eindhoven</a><a href="/loodgieter-tilburg/">Tilburg</a><a href="/loodgieter-groningen/">Groningen</a><a href="/loodgieter-klundert/">Klundert</a><a href="/over-ons/">Over ons</a><a href="/contact/">Contact</a><a href="/veelgestelde-vragen/">Veelgestelde vragen</a><a href="/privacy/">Privacy</a></div></div><a href="https://www.starlocal.nl/" target="_blank" rel="noopener noreferrer">Star Local</a></div></footer>'''
floatlink=s.split('<a class="whatsapp-float"',1)[1].split('</a>',1)[0]
floatlink='<a class="whatsapp-float"'+floatlink+'</a>'
headprefix='''<!doctype html><html lang="nl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">'''
favicon=s.split('<link rel="icon"',1)[1].split('>',1)[0]
favicon='<link rel="icon"'+favicon+'>'
form='<form class="card" id="leadForm">'+s.split('<form class="card" id="leadForm">',1)[1].split('</form>',1)[0]+'</form>'
form_script='<script>'+s.split('<script>',1)[1].split('</script>',1)[0]+'</script>'
def page(route,title,description,hero,lead,body,hero_class=''):
    if route == 'loodgieter-groningen':
        hero = 'Loodgieter Groningen'
    city=({'denhaag':'Den Haag'}.get(route.split('loodgieter-',1)[1],route.split('loodgieter-',1)[1].capitalize())) if route.startswith('loodgieter-') else ''
    local_form=form.replace('placeholder="Bijv. Breda"',f'value="{city}"' if city else 'placeholder="Bijv. Breda"')
    local_floatlink = floatlink
    if route == 'loodgieter-groningen':
        local_floatlink = floatlink.replace('text=Hallo%2C%20ik%20heb%20een%20vraag%20over%20een%20loodgietersklus.', 'text=Hallo%2C%20ik%20heb%20een%20loodgietersklus%20in%20Groningen.').replace('aria-label="Stel je vraag via WhatsApp"', 'aria-label="Vraag loodgieterswerk in Groningen aan via WhatsApp"')
    preload=f'<link rel="preload" as="image" href="/hero-{route.split("loodgieter-",1)[1]}.webp">' if route.startswith('loodgieter-') else ''
    canonical=f'https://loodgietervakmannen.nl/{route}/'
    image=f'https://loodgietervakmannen.nl/hero-{route.split("loodgieter-",1)[1]}.webp' if city else 'https://loodgietervakmannen.nl/og.png'
    social=(f'<meta property="og:type" content="website"><meta property="og:site_name" content="Loodgieter Vakmannen">'
            f'<meta property="og:url" content="{canonical}"><meta property="og:title" content="{escape(title,quote=True)}">'
            f'<meta property="og:description" content="{escape(description,quote=True)}"><meta property="og:image" content="{image}">'
            f'<meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="{escape(title,quote=True)}">'
            f'<meta name="twitter:description" content="{escape(description,quote=True)}"><meta name="twitter:image" content="{image}">')
    markup=f'''{headprefix}<title>{escape(title)}</title><meta name="description" content="{escape(description,quote=True)}"><link rel="canonical" href="https://loodgietervakmannen.nl/{route}/">{favicon}{preload}{social}<style>{css}</style></head><body>{nav}<main><section class="subhero form-hero {hero_class}"><div class="wrap"><div class="page-hero-copy"><div class="bread"><a href="/">Home</a> / {escape(hero)}</div><h1>{escape(hero)}</h1><p>{escape(lead)}</p></div><div id="aanvraag" class="hero-form">{local_form}</div></div></section>{body}</main>{footer}{local_floatlink}{form_script}</body></html>'''
    path=root/route/'index.html';path.parent.mkdir(parents=True,exist_ok=True);path.write_text(markup)
# Place pages have distinct, modest content. No invented availability, credentials or response promises.
local={
'breda':dict(city='Breda',intro='Heb je in Breda een lekkage, verstopte afvoer of werk aan sanitair? Omschrijf de klus en geef je wijk of buurt door in je WhatsApp-bericht.',detail='Of de klus nu in het centrum, Ginneken, Princenhage, Haagse Beemden of een andere Bredase wijk ligt: de locatie en een duidelijke omschrijving helpen om je aanvraag gericht te beoordelen.',timing='Vermeld bij wateroverlast waar het water vandaan komt en of je de hoofdkraan al hebt kunnen afsluiten.'),
'amsterdam':dict(city='Amsterdam',intro='Een loodgietersklus in Amsterdam? Geef door wat er aan de hand is, in welk stadsdeel de klus plaatsvindt en wanneer je hulp zoekt.',detail='Bij een woning in Centrum, Noord, Oost, Zuid, West, Nieuw-West of Zuidoost maakt het voor een aanvraag uit waar en hoe het probleem bereikbaar is. Noem daarom je stadsdeel en, als relevant, de verdieping.',timing='Heb je een lekkage in een appartement? Beschrijf ook of het water bij buren of in een andere ruimte zichtbaar is.'),
'rotterdam':dict(city='Rotterdam',intro='Van een lekkende leiding tot werk aan sanitair: beschrijf je loodgietersklus in Rotterdam en stuur je aanvraag via WhatsApp.',detail='Rotterdam kent uiteenlopende woningen, van appartementen in het centrum tot oudere huizen in wijken als Delfshaven en gezinswoningen verder van de binnenstad. Vermeld daarom je wijk, woningtype en waar de leiding of afvoer bereikbaar is.',timing='Bij een lekkage in een hoogbouwappartement helpt het om de verdieping en eventuele gevolgen voor onderliggende ruimtes te noemen.'),
'utrecht':dict(city='Utrecht',intro='Een loodgieter nodig in Utrecht? Vertel of het om een lekkage, verstopping of aanpassing aan de installatie gaat.',detail='Een klus in een ouder pand rond de binnenstad kan een andere toegang tot leidingen hebben dan een woning in Leidsche Rijn. Noem je buurt en geef aan of de werkplek achter een kast, tegelwand of keukenblok ligt.',timing='Loopt een afvoer in een gedeelde woning of appartement over? Beschrijf ook welke andere afvoeren nog wel werken.'),
'denhaag':dict(city='Den Haag',intro='Beschrijf je loodgietersklus in Den Haag en geef aan waar het probleem zich in de woning bevindt.',detail='In Den Haag staan zowel oudere stadswoningen als appartementen en nieuwere huizen. Geef aan of de klus in de keuken, badkamer of bij een leiding in een gemeenschappelijke ruimte zit, plus je wijk of straat.',timing='Bij wateroverlast in een bovenwoning is het handig te melden of de lekkage ook bij benedenburen zichtbaar is.'),
'eindhoven':dict(city='Eindhoven',intro='Een verstopping, lekkage of nieuwe aansluiting in Eindhoven? Stuur de bijzonderheden van je klus door.',detail='Of je nu in een appartement rond het centrum of een gezinswoning in een andere Eindhovense wijk woont: geef aan welk toestel of welke afvoer problemen geeft en of de hoofdkraan bereikbaar is.',timing='Bij het plaatsen van nieuw sanitair helpt het om de bestaande aansluiting en de gewenste wijziging kort te beschrijven.'),
'tilburg':dict(city='Tilburg',intro='Een loodgietersklus in Tilburg? Laat weten welk probleem je ziet en wanneer je hulp zoekt.',detail='Een lekkende keukenkraan, een verstopte douche of leidingwerk bij een verbouwing vragen elk om andere informatie. Vermeld je Tilburgse wijk en of het probleem in een oudere woning, appartement of nieuwbouwwoning speelt.',timing='Bij een terugkerende verstopping helpt het om te vertellen sinds wanneer die optreedt en welke afvoeren tegelijk langzaam doorlopen.'),
'groningen':dict(city='Groningen',intro='Loodgieterswerk nodig in Groningen? Beschrijf de situatie, de locatie en het gewenste moment.',detail='In de binnenstad, een gedeeld huis of een appartement kan een leiding of afvoer lastig bereikbaar zijn. Geef aan om welke ruimte het gaat, of andere bewoners last hebben en waar de hoofdkraan zit als je dat weet.',timing='Bij een lekkage in een gedeelde woning kun je aangeven wie er toegang tot de ruimte heeft en of er al water is afgesloten.'),
'klundert':dict(city='Klundert',intro='Een lekkage, verstopping of klus aan sanitair in Klundert? Vertel waar het probleem zit en stuur je aanvraag via WhatsApp.',detail='Klundert is een vestingstad in de gemeente Moerdijk. Of je klus nu in de oudere kern of in een andere buurt ligt: vermeld je straat of buurt en beschrijf waar leidingen of afvoeren bereikbaar zijn.',timing='Bij een vochtplek helpt het om aan te geven of die na gebruik van de badkamer of keuken verschijnt. Bij een verstopping: noem de afvoer en of andere afvoeren nog werken.')}
for slug,d in local.items():
    c=d['city']
    body=f'''<section class="section"><div class="wrap split"><div><span class="kicker">Loodgietersklus in {c}</span><h2>Welke hulp zoek je?</h2><p class="lead">{d['detail']}</p><p class="lead">{d['timing']}</p><a class="primary" href="#aanvraag">Doe een aanvraag voor {c} <span aria-hidden="true">↗</span></a></div><div class="card"><h3>Dit kun je doorgeven</h3><ul><li>Lekkage aan kraan, leiding of afvoer</li><li>Verstopte gootsteen, douche of toilet</li><li>Werk aan leidingen of sanitair</li><li>Een andere loodgietersklus</li></ul><p class="note">Een aanvraag is vrijblijvend. Beschikbaarheid en afspraken worden na contact besproken.</p></div></div></section><section class="section soft"><div class="wrap intro"><span class="kicker">Zo werkt het</span><h2>Beschrijf je klus in een paar stappen</h2><p class="lead">Kies bovenaan het soort klus, vul je naam en plaats in en licht het probleem toe. WhatsApp opent met het bericht klaar om door jou te versturen. Zet <strong>{c}</strong> bij de plaats en voeg eventueel een foto toe in WhatsApp.</p><a class="primary" href="#aanvraag">Naar het aanvraagformulier <span aria-hidden="true">↗</span></a></div></section>'''
    enhanced = city_details(slug)
    title = f'Loodgieter {c} | Beschrijf je klus | Loodgieter Vakmannen'
    description = f'Een loodgieter nodig in {c}? Beschrijf je lekkage, verstopping of installatieklus en stuur je aanvraag via WhatsApp.'
    if enhanced:
        title, description, extra = enhanced
        body += extra
    page('loodgieter-'+slug,title,description,f'Loodgieter nodig in {c}?',d['intro'],body,hero_class='city-hero city-'+slug)
page('over-ons','Over ons | Loodgieter Vakmannen','Lees hoe Loodgieter Vakmannen aanvragen voor loodgietersklussen helpt doorsturen via WhatsApp.','Over Loodgieter Vakmannen','Een eenvoudige manier om een loodgietersklus helder te beschrijven en contact te leggen.', '''<section class="section"><div class="wrap content"><span class="kicker">Wie zit erachter?</span><h2>Een initiatief van Star Local</h2><p>Loodgieter Vakmannen is een website van Star Local. We helpen bezoekers hun vraag over lekkages, verstoppingen en installatiewerk overzichtelijk te formuleren. Via het formulier opent een vooraf ingevuld WhatsApp-bericht; je bepaalt zelf of je dat bericht verstuurt.</p><p>De website is een aanvraagpunt en voert zelf geen loodgieterswerk uit. Een aanvraag is geen afspraak. Beschikbaarheid, werkzaamheden en voorwaarden worden pas in het contact besproken.</p><h2>Wat helpt bij een goede aanvraag?</h2><p>Vermeld de plaats, het soort klus, een korte omschrijving en wanneer je hulp zoekt. Een foto kun je daarna via WhatsApp toevoegen.</p><a class="primary" href="#aanvraag">Beschrijf je klus <span aria-hidden="true">↗</span></a></div></section>''')
page('contact','Contact | Loodgieter Vakmannen','Contact opnemen over een loodgietersklus? Stuur je vraag via WhatsApp of mail Star Local.','Contact','Stuur je vraag met de locatie en een korte omschrijving van je klus.','''<section class="section"><div class="wrap split"><div class="card"><h2>Een loodgietersklus melden</h2><p class="lead">Gebruik het aanvraagformulier. Je bericht opent in WhatsApp en wordt pas verstuurd wanneer jij op verzenden drukt.</p><a class="primary" href="#aanvraag">Naar het aanvraagformulier <span aria-hidden="true">↗</span></a></div><div class="card"><h2>Andere vraag?</h2><p class="lead">Voor vragen over deze website kun je Star Local bereiken via WhatsApp of e-mail.</p><p><a href="https://wa.me/31684002350" target="_blank" rel="noopener noreferrer">WhatsApp: 06 8400 2350</a><br><a href="mailto:info@starlocal.nl">info@starlocal.nl</a></p></div></div></section>''')
page('veelgestelde-vragen','Veelgestelde vragen | Loodgieter Vakmannen','Antwoorden over aanvragen, WhatsApp, beschikbaarheid en kosten bij Loodgieter Vakmannen.','Veelgestelde vragen','Praktische antwoorden voordat je een aanvraag verstuurt.','''<section class="section"><div class="wrap content faq"><details><summary>Hoe verstuur ik een aanvraag?</summary><p>Vul het formulier bovenaan deze pagina in. Daarna opent WhatsApp met je gegevens en omschrijving. Controleer het bericht en druk daar op verzenden.</p></details><details><summary>Is het invullen van het formulier een afspraak?</summary><p>Nee. Je stuurt een vraag. Of een klus kan worden opgepakt, en onder welke voorwaarden, wordt in het verdere contact besproken.</p></details><details><summary>Kan ik foto's meesturen?</summary><p>Ja. Nadat WhatsApp opent, kun je zelf foto's aan het gesprek toevoegen.</p></details><details><summary>Wat moet ik bij een lekkage vermelden?</summary><p>Vertel waar het water zichtbaar is, sinds wanneer het probleem speelt en of je de watertoevoer kunt afsluiten. Bij ernstige wateroverlast: handel eerst om schade te beperken.</p></details><details><summary>Wat kost een loodgieter?</summary><p>Dat hangt af van de klus en de gemaakte afspraken. Op deze website staat geen vast tarief en een aanvraag geeft geen prijsopgave.</p></details><p><a class="primary" href="#aanvraag">Doe een aanvraag <span aria-hidden="true">↗</span></a></p></div></section>''')
page('privacy','Privacy | Loodgieter Vakmannen','Lees hoe Loodgieter Vakmannen met gegevens uit een aanvraag en WhatsApp-contact omgaat.','Privacy','Hoe gegevens bij een aanvraag via deze website worden gebruikt.','''<section class="section"><div class="wrap content"><h2>Wie beheert deze website?</h2><p>Loodgieter Vakmannen is een initiatief van Star Local. Voor vragen over je gegevens kun je mailen naar <a href="mailto:info@starlocal.nl">info@starlocal.nl</a>.</p><h2>Het aanvraagformulier</h2><p>Het formulier maakt in je browser een WhatsApp-bericht van de gegevens die je invult: soort klus, plaats, naam, omschrijving en gewenst moment. De website slaat die invoer niet op in een eigen database. Het bericht wordt pas via WhatsApp verstuurd wanneer je daar zelf op verzenden drukt.</p><h2>WhatsApp en contact</h2><p>Als je een bericht verstuurt, worden de inhoud en je contactgegevens gebruikt om op je aanvraag te reageren en deze te beoordelen. WhatsApp verwerkt berichten volgens zijn eigen voorwaarden en privacybeleid. Vermeld liever geen gegevens die niet nodig zijn voor je klus.</p><h2>Je gegevens</h2><p>Wil je weten welke gegevens uit je contact zijn bewaard, of wil je vragen om verwijdering? Mail <a href="mailto:info@starlocal.nl">info@starlocal.nl</a>. Gegevens kunnen worden bewaard zolang dat nodig is om de aanvraag en eventueel vervolgcontact af te handelen of om aan toepasselijke verplichtingen te voldoen.</p><p>Deze tekst beschrijft de huidige WhatsApp-aanvraagroute. Bij uitbreiding met andere formulieren of meetdiensten wordt deze pagina bijgewerkt.</p></div></section>''')
# Add navigation and useful city links to existing home while preserving the original lead flow.
oldheader=s.split('<header class="top">',1)[1].split('</header>',1)[0]
s=s.replace('<header class="top">'+oldheader+'</header>',nav)
oldfooter=s.split('<footer class="foot">',1)[1].split('</footer>',1)[0]
s=s.replace('<footer class="foot">'+oldfooter+'</footer>',footer)
if '<span class="kicker">Per gemeente</span>' not in s:
 s=s.replace('</main>', '''<section class="section"><div class="wrap"><div class="intro"><span class="kicker">Per gemeente</span><h2>Bekijk je plaats</h2><p class="lead">We beginnen met informatie voor Breda en Amsterdam. Geef altijd je exacte plaats door bij een aanvraag.</p></div><div class="linkcards"><a class="linkcard" href="/loodgieter-breda/"><strong>Loodgieter Breda</strong><p>Een klus in Breda? Lees welke details je kunt doorgeven.</p><span>Bekijk Breda ↗</span></a><a class="linkcard" href="/loodgieter-amsterdam/"><strong>Loodgieter Amsterdam</strong><p>Een klus in Amsterdam? Beschrijf ook je stadsdeel en situatie.</p><span>Bekijk Amsterdam ↗</span></a></div></div></section></main>''')
city_cards=''.join(f'<a class="linkcard" href="/loodgieter-{slug}/"><strong>Loodgieter {data["city"]}</strong><p>{data["intro"]}</p><span>Bekijk {data["city"]} ↗</span></a>' for slug,data in local.items())
city_section='<section class="section" id="gemeenten"><div class="wrap"><div class="intro"><span class="kicker">Per gemeente</span><h2>Bekijk je plaats</h2><p class="lead">Lees welke gegevens nuttig zijn voor een aanvraag in jouw gemeente. Vermeld je exacte locatie in het formulier.</p></div><div class="linkcards">'+city_cards+'</div></div></section>'
import re
s=re.sub(r'<section class="section"(?: id="gemeenten")?><div class="wrap"><div class="intro"><span class="kicker">Per gemeente</span>.*?</section>', '', s, flags=re.S)
s=s.replace('</main>',city_section+'</main>',1)
s=s.split('<style>',1)[0]+'<style>'+css+'</style>'+s.split('</style>',1)[1]
index.write_text(s)

# Retain AdSense when regenerating existing pages or adding new ones.
from adsense import install as install_adsense
install_adsense()
